export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_RENTALS_DETAILS_SUCCESS = 'FETCH_RENTAL_DETAILS_SUCCESS';
export const FETCH_RENTALS_DETAILS_INIT = 'FETCH_RENTAL_DETAILS_INIT';
export const FETCH_RENTALS_SUCCESS = 'FETCH_RENTALS_SUCCESS';
